# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/kmironp/Desktop/Szakdoga_vegso/Kodok/ArtySimpleSoC/ArtySOC/Arty-A7-35-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CORTEXM1_AXI_0_4/design_1_CORTEXM1_AXI_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CORTEXM1_AXI_0_4 || ORIG_REF_NAME==design_1_CORTEXM1_AXI_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_4/design_1_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_4 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_3/design_1_axi_bram_ctrl_0_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_bram_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_bram_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_3 || ORIG_REF_NAME==design_1_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2 || ORIG_REF_NAME==design_1_axi_smc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_3 || ORIG_REF_NAME==design_1_clk_wiz_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_iobuffer_0_3/design_1_iobuffer_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_iobuffer_0_3 || ORIG_REF_NAME==design_1_iobuffer_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_4/design_1_reset_inv_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_4 || ORIG_REF_NAME==design_1_reset_inv_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_3/design_1_rst_clk_wiz_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_3 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_3/design_1_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_3 || ORIG_REF_NAME==design_1_xlconstant_0_3} -quiet] -quiet

# XDC: c:/Users/kmironp/Desktop/Szakdoga_vegso/Kodok/ArtySimpleSoC/ArtySOC/ArtySOC.gen/sources_1/bd/design_1/design_1_ooc.xdc
